### ISSUE TITLE
Scaled FlxUISprite without antialiasing?

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel-ui#111]
Is it possible? I don't see where to disable antialiasing when a sprite is scaled in xml definition.

**Comment by larsiusprime** [comment]
should be try setting the attribute smooth="false"

**Comment by guifes** [comment]
Did not work, unless I did it wrong.

```haxe
<sprite src="ui/duncan" x="55%" y="50%" width="72" height="96" smooth="false"/>
```

**Comment by larsiusprime** [comment]
I'll look into it on monday, should be a simple fix if it's not a syntax
issue.

On Sat, Jun 27, 2015 at 1:12 AM, Guilherme <notifications@github.com> wrote:

> Did not work, unless I did it wrong.
>
> <sprite src="ui/duncan" x="55%" y="50%" width="72" height="96" smooth="false"/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFlixel/flixel-ui/issues/111#issuecomment-115972451>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by guifes** [comment]
Anything?

**Comment by guifes** [comment]
Anything on this issue?

**Comment by larsiusprime** [comment]
Sorry for the delay, looking into it now.

**Comment by larsiusprime** [comment]
Done.

Turns out there was not functionality for reading smoothing from the xml data. The actual scaling operation happens before the sprite itself is constructed, so the final pixels in your sprite won't respond to the FlxSprite.antialiasing flag.

So I'm adding the ability to just put `smooth="false"` in your sprite tag. `antialias="false"` will also work. 

The "smooth" tag can be applied to a sprite tag, or in a `<scale>` tag.

**Comment by guifes** [comment]
Thanks a lot!!!
