### ISSUE TITLE
All UI classes should be in the same haxelib and in same package

### ISSUE THREAD

**Issue by buckle2000** [HaxeFlixel/flixel-ui#173]
Why there are ui classes in `flixel`, `flixel-addons` and `flixel-ui`?
Why some of them are under `flixel.ui.*`, some are under `flixel.addons.ui.*`?

**Comment by MSGhero** [comment]
Flixel-ui is a part of Flixel-addons (`flixel.addons.ui == flixel-ui`), but it has its own repo since it's pretty involved. Flixel's default UI package is just for basic UI stuff, like a button. This one is if you want to do fancier things.

**Comment by buckle2000** [comment]
But there are some classes remaining here:
https://github.com/HaxeFlixel/flixel-addons/tree/dev/flixel/addons/ui

**Comment by MSGhero** [comment]
There's a lot of random stuff in addons that I don't think anyone has ever seen before

**Comment by Gama11** [comment]
>All UI classes should be in the same haxelib and in same package

I disagree. Some UI components like `FlxButton` are so useful that almost every game needs them, and it would be silly to require including flixel-ui just for that. On the flipside, most games don't need all the advanced features flixel-ui has.

The classes in flixel-addons are in a bit of a weird place right now, they're mostly there because they didn't originate from Lars' flixel-ui AS3 port, but are still not considered useful enough for the core library.
