### ISSUE TITLE
xml new FlxUI chrome is adding extra words to src

### ISSUE THREAD

**Issue by gltovar** [HaxeFlixel/flixel-ui#77]
I have a simple xml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
    <data>
        <chrome id="back" src="assets/images/chrome" slice9="4,4,8,8" width="400" height="200"/>
        <text id="title" use_def="sans12c" x="0" y="5" width="back.width" text="TEST" align="center">
            <anchor x="back.left" x-flush="left" y="back.top" y-flush="top"/>
        </text>
    </data>
```

and in a state i have a:
var test:FlxUI = new FlxUI( U.xml("test") );

now when everything is getting parsed, when it gets time to load the chrome
FlxUI._load9SliceSprite()  the line:
src = U.xml_gfx(data.x, "src")  

goes to U.gfx() instead leading it to: 
get_gfx(id)

where it returns:
"assets/gfx/"+ str + ".png"; // assets/gfx/assets/images/chrome.png

not exactly sure why the code choses to go to U.gfx instead of U.xml_gfx when stepping though.

**Comment by larsiusprime** [comment]
Geez, old issues I need to clean up.

So this is actually by design. The default path is setup to be "assets/gfx" by default according to the documentation. If you want an absolute path you should prepend "RAW:" to your src, so "RAW:assets/images/chrome".

I will consider redesigning this in the future if I can find a way not to break existing projects.
